project:
  type: website
  output-dir: docs

website:
  title: "/STC-CGIAR workshop"
  site-url: https://jelmerp.github.io/cabana-workshop
  repo-url: https://github.com/jelmerp/cabana-workshop
  page-navigation: true
  back-to-top-navigation: true
  favicon: "img/UNTRM_favicon.png"
  navbar:
    logo: "img/CABANA_small.png"
    left:
      - href: index.qmd
        icon: house
        text: " "
      - text: "Wed Feb 7"
        menu: 
          - text: "Supercomputing & OSC"
            href: 01_osc.qmd
          - text: "VS Code"
            href: 02_vscode.qmd
          - text: "Unix shell refresher"
          - text: "FASTQ files and quality control"
          - text: "_Phytophthora_ amplicon sequencing"
            href: 05_amplicon.qmd
      - text: "Thu Feb 8"
        menu: 
          - text: "Bacterial genome analysis (slides)"
          - text: "Shell scripts, batch jobs, and loops"
          - text: "Intro to Bactopia"
          - text: "Running Bactopia"
          - text: "Interpeting the Bactopia results"
    right:
      - text: Other Pages
        menu:
          - text: "Homework"
            href: homework.qmd
          - text: "Opening a Unix Shell at OSC"
            href: open_shell.qmd
          - text: "Starting an RStudio session at OSC"
            href: rstudio.qmd
          - text: "Overview of common Unix shell commands"
      - text: About
        href: about.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/jelmerp/cabana-workshop
          - text: Report an Issue
            url:  https://github.com/jelmerp/cabana-workshop/issues/new
format:
  html:
    highlight-style: atom-one
    theme: yeti
    css: styles.css
    toc: true
    number-sections: true
    number-depth: 3
    grid:
      body-width: 900px

editor: visual
