project:
  type: website
  output-dir: docs

website:
  title: "/STC-CGIAR workshop"
  site-url: https://jelmerp.github.io/cabana-workshop
  repo-url: https://github.com/jelmerp/cabana-workshop
  page-navigation: true
  back-to-top-navigation: true
  favicon: "img/UNTRM_favicon.png"
  navbar:
    logo: "img/CABANA_small.png"
    left:
      - href: index.qmd
        icon: house
        text: " "
      - text: "Wed Feb 7"
        menu: 
          - text: "Supercomputing & OSC"
            href: 01_osc.qmd
          - text: "VS Code"
            href: 02_vscode.qmd
          - text: "Unix shell refresher"
            href: 03_shell.qmd
          - text: "-----------"
          - text: "_Phytophthora_ amplicon sequencing"
            href: 04_amplicon.qmd
      - text: "Thu Feb 8"
        menu: 
          - text: "Bacterial whole-genome sequencing (slides)"
            href: bact_slides.qmd
          - text: "Read QC & preprocessing"
            href: 05_preprocess.qmd
          - text: "Genome assembly and assembly QC"
            href: 06_assembly.qmd
          - text: "Genome annotation"
            href: 07_annotation.qmd
    right:
      - text: "Homework"
        href: homework.qmd
      - text: Reference Pages
        menu:
          - text: "Opening a Unix shell at OSC"
            href: open_shell.qmd
          - text: "Starting an RStudio session at OSC"
            href: rstudio.qmd
          - text: "---------------"
          - text: "Continued Unix shell intro"
            href: ref_shell2.qmd
          - text: "Unix shell overview/reference"
            href: ref_shell.qmd
          - text: "--------------"
          - text: "Software management"
            href: ref_software.qmd
          - text: "Data management"
            href: ref_data.qmd
      - text: About
        href: about.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/jelmerp/cabana-workshop
          - text: Report an Issue
            url:  https://github.com/jelmerp/cabana-workshop/issues/new
format:
  html:
    highlight-style: atom-one
    theme: yeti
    css: styles.css
    toc: true
    number-sections: true
    number-depth: 3
    grid:
      body-width: 900px

editor: source
